# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Текст задания')),
                ('score_to_pass', models.IntegerField(verbose_name='Оценка для сдачи')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('score_to_pass', models.IntegerField(verbose_name='Оценка для сдачи')),
                ('function_to_evaluate', models.CharField(max_length=200, verbose_name='Функция оценивания')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Competence', verbose_name='Компетенция')),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceLevelScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Оценка по уровню 1 для получения уровня 2')),
                ('competence_level_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lower_levels', to='dtb.CompetenceLevel', verbose_name='Уровень компетенции 1')),
                ('competence_level_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='higher_levels', to='dtb.CompetenceLevel', verbose_name='Уровень компетенции 2')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleCompetenceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.CompetenceLevel', verbose_name='Уровень компетенции')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Module', verbose_name='Модуль')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_dependencies', to='dtb.Module', verbose_name='Зависимый модуль')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_dependents', to='dtb.Module', verbose_name='Модуль')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCompetenceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('type', models.CharField(choices=[('actiity_exam', 'ACTIVITY_EXAM'), ('tasks', 'TASKS')], default='tasks', max_length=15)),
                ('competence_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.CompetenceLevel', verbose_name='Уровень компетенции')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Person', verbose_name='Человек')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCompetenceLevelChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.CompetenceLevel', verbose_name='Уровень компетенции')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Person', verbose_name='Человек')),
            ],
        ),
        migrations.CreateModel(
            name='PersonModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(verbose_name='Пройден')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Module', verbose_name='Модуль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Person', verbose_name='Человек')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='RoleCompetenceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес компетенции для роли')),
                ('competence_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.CompetenceLevel', verbose_name='Уровень компетенции')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Role', verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Module', verbose_name='Модуль')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Текст задания')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Ответ на задание')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Максимальный балл за задание')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес задания')),
                ('competence_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.CompetenceLevel', verbose_name='Уровень компетенции')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Module', verbose_name='Модуль')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Оценка')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Person', verbose_name='Человек')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Task', verbose_name='Задание')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.Role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='activityexam',
            name='competence_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtb.CompetenceLevel', verbose_name='Уровень кометенции'),
        ),
        migrations.AlterUniqueTogether(
            name='taskresult',
            unique_together=set([('person', 'task')]),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('competence_level', 'module', 'task_text')]),
        ),
        migrations.AlterUniqueTogether(
            name='rolecompetencelevel',
            unique_together=set([('role', 'competence_level')]),
        ),
        migrations.AlterUniqueTogether(
            name='personmodule',
            unique_together=set([('person', 'module')]),
        ),
        migrations.AlterUniqueTogether(
            name='personcompetencelevelchoice',
            unique_together=set([('person', 'competence_level')]),
        ),
        migrations.AlterUniqueTogether(
            name='personcompetencelevel',
            unique_together=set([('person', 'competence_level', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='moduledependency',
            unique_together=set([('module', 'dependent_module')]),
        ),
        migrations.AlterUniqueTogether(
            name='modulecompetencelevel',
            unique_together=set([('module', 'competence_level')]),
        ),
        migrations.AlterUniqueTogether(
            name='competencelevelscale',
            unique_together=set([('competence_level_1', 'competence_level_2')]),
        ),
        migrations.AlterUniqueTogether(
            name='competencelevel',
            unique_together=set([('competence', 'level')]),
        ),
        migrations.AlterUniqueTogether(
            name='activityexam',
            unique_together=set([('competence_level', 'task')]),
        ),
    ]
