# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('name', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('module', 'name', 'type')]),
        ),
    ]
